workflows:
  ios-release:
    name: Tactical Eleven iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: manual
        credentials:
          ios_distribution:
            certificate: $FCI_IOS_DISTRIBUTION_CERTIFICATE
            certificate_password: $FCI_IOS_DISTRIBUTION_CERTIFICATE_PASSWORD
            provisioning_profile: $FCI_IOS_PROVISIONING_PROFILE
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
